language: node_js
sudo: required
node_js: 
  - 7.9.0

cache:
  directories:
    - node_modules

branches:
  only:
    - hexo_blog

before_install:
  - npm install -g hexo-cli

# S: Build Lifecycle
install:
  - npm install
  - npm install hexo-deployer-git --save

before_script:
 # - npm install -g gulp

script:
  - hexo clean
  - hexo generate

after_script:
  - git config user.name "jixiaoyong"
  - git config user.email "jixiaoyong1995@gmail.com"
  # - git config --global github.user jixiaoyong      
  # - git config --global github.token ${GH_TOKEN}
  - pwd
  - ls
  - cd ..
  - mkdir publish
  - cd publish
  - git clone https://${GH_TOKEN}@github.com/jixiaoyong/jixiaoyong.github.io.git
  - rm -rf ./jixiaoyong.github.io/blog/*
  - cd ..
  - cp -rf jixiaoyong.github.io/public/* publish/jixiaoyong.github.io/blog/
  - cd publish/jixiaoyong.github.io/
  - git add .
  - git commit -m "auto update by www.travis-ci.org"
  - git push

# E: Build LifeCycle
